package com.backend.Ticket.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import io.swagger.v3.oas.annotations.media.Schema;

@Entity
public class TrainStation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "ID of the train station, auto-generated by the database", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Name of the train station", example = "Central Station", required = true)
    private String stationName;

    @Schema(description = "Stop number of the train station", example = "1", required = true)
    private int stopNumber;

    @Schema(description = "Fare amount from this station", example = "15.50", required = true)
    private double fareAmount;

    @Schema(description = "duration from source to destination in minutes", example = "1.50", required = true)
    private double duration;

    @Schema(description = "name of source station", example = "kawasaki station", required = true)
    private String sourceStation;

    // Default constructor
    public TrainStation() {
    }

    // Getters and Setters
    public String getStationName() {
        return stationName;
    }

    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getStopNumber() {
        return stopNumber;
    }

    public void setStopNumber(int stopNumber) {
        this.stopNumber = stopNumber;
    }

    public double getFareAmount() {
        return fareAmount;
    }

    public void setFareAmount(double fareAmount) {
        this.fareAmount = fareAmount;
    }

    public String getsourceStation() {
        return sourceStation;
    }

    public void setSourceStation(String sourceStation) {
        this.sourceStation= sourceStation;
    }

    public double getDuration(){return duration;}
    public void setDuration(double duration){
        this.duration= duration;
    }
}
