//package com.backend.Ticket.entity;
//
//import jakarta.persistence.Entity;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.GenerationType;
//import jakarta.persistence.Id;
//import java.time.LocalDateTime;
//
//@Entity
//public class Transactions {
//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long transactionId;
//    private String userFirstname;
//    private String userLastname;
//    private Long trainStationId;
//    private String modeOfPayment;
//    private LocalDateTime transactionDateTime;
//    private double amount;
//
//    // Default constructor
//    public Transactions() {
//    }
//
//    // Getters and Setters
//    public Long getTransactionId() {
//        return transactionId;
//    }
//
//    public void setTransactionId(Long transactionId) {
//        this.transactionId = transactionId;
//    }
//
//    public String getUserFirstname() {
//        return userFirstname;
//    }
//
//    public void setUserFirstname(String userFirstname) {
//        this.userFirstname = userFirstname;
//    }
//
//    public String getUserLastname() {
//        return userLastname;
//    }
//
//    public void setUserLastname(String userLastname) {
//        this.userLastname = userLastname;
//    }
//
//    public Long getTrainStationId() {
//        return trainStationId;
//    }
//
//    public void setTrainStationId(Long trainStationId) {
//        this.trainStationId = trainStationId;
//    }
//
//    public String getModeOfPayment() {
//        return modeOfPayment;
//    }
//
//    public void setModeOfPayment(String modeOfPayment) {
//        this.modeOfPayment = modeOfPayment;
//    }
//
//    public LocalDateTime getTransactionDateTime() {
//        return transactionDateTime;
//    }
//
//    public void setTransactionDateTime(LocalDateTime transactionDateTime) {
//        this.transactionDateTime = transactionDateTime;
//    }
//
//    public double getAmount() {
//        return amount;
//    }
//
//    public void setAmount(double amount) {
//        this.amount = amount;
//    }
//}


package com.backend.Ticket.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class Transactions {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Transaction ID, auto-generated by the database", accessMode = Schema.AccessMode.READ_ONLY)
    private Long transactionId;

    @Schema(description = "First name of the user", example = "John", required = true)
    private String userFirstname;

    @Schema(description = "Last name of the user", example = "Doe", required = true)
    private String userLastname;

    @Schema(description = "ID of the train station where the transaction occurred", example = "101", required = true)
    private Long trainStationId;

    @Schema(description = "Mode of payment used in the transaction", example = "Credit Card", required = true)
    private String modeOfPayment;

    @Schema(description = "Date and time of the transaction, auto-set by the system", accessMode = Schema.AccessMode.READ_ONLY, example = "2025-01-27T10:15:30")
    private LocalDateTime transactionDateTime;

    @Schema(description = "Total amount for the transaction", example = "50.75", required = true)
    private double amount;

    // Default constructor
    public Transactions() {
        this.transactionDateTime = LocalDateTime.now(); // Automatically set the current date and time
    }

    // Getters and setters
    public Long getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    public String getUserFirstname() {
        return userFirstname;
    }

    public void setUserFirstname(String userFirstname) {
        this.userFirstname = userFirstname;
    }

    public String getUserLastname() {
        return userLastname;
    }

    public void setUserLastname(String userLastname) {
        this.userLastname = userLastname;
    }

    public Long getTrainStationId() {
        return trainStationId;
    }

    public void setTrainStationId(Long trainStationId) {
        this.trainStationId = trainStationId;
    }

    public String getModeOfPayment() {
        return modeOfPayment;
    }

    public void setModeOfPayment(String modeOfPayment) {
        this.modeOfPayment = modeOfPayment;
    }

    public LocalDateTime getTransactionDateTime() {
        return transactionDateTime;
    }

    public void setTransactionDateTime(LocalDateTime transactionDateTime) {
        this.transactionDateTime = transactionDateTime;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }
}

