//package com.backend.Ticket.entity;
//
//import io.swagger.v3.oas.annotations.media.Schema;
//import jakarta.persistence.*;
//
//import javax.smartcardio.Card;
//import java.time.LocalDateTime;
//
//@Entity
//public class Transactions {
//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Schema(description = "Transaction ID, auto-generated by the database", accessMode = Schema.AccessMode.READ_ONLY)
//    private Long transactionId;
//
//    @Schema(description = "First name of the user", example = "John", required = true)
//    private String userFirstname;
//
//    @Schema(description = "Last name of the user", example = "Doe", required = true)
//    private String userLastname;
//
//    @Schema(description = "ID of the train station where the transaction occurred", example = "101", required = true)
//    private Long trainStationId;
//
//    @Schema(description = "Mode of payment used in the transaction", example = "Credit Card", required = true)
//    private String modeOfPayment;
//
//    @Schema(description = "Date and time of the transaction, auto-set by the system", accessMode = Schema.AccessMode.READ_ONLY, example = "2025-01-27T10:15:30")
//    private LocalDateTime transactionDateTime;
//
//    @Schema(description = "Total amount for the transaction", example = "50.75", required = true)
//    private double amount;
//
//    @Schema(description = "Destination station name", example = "Ayala Avenue")
//    private String destinationName;  // New field for destination station name
//
//    @Schema(description = "Card number", example = "1111222233334444")
//    private String CardNumber;
//
//    // Default constructor
//    public Transactions() {
//        this.transactionDateTime = LocalDateTime.now(); // Automatically set the current date and time
//    }
//
//    // Getters and setters
//    public Long getTransactionId() {
//        return transactionId;
//    }
//
//    public void setTransactionId(Long transactionId) {
//        this.transactionId = transactionId;
//    }
//
//    public String getUserFirstname() {
//        return userFirstname;
//    }
//
//    public void setUserFirstname(String userFirstname) {
//        this.userFirstname = userFirstname;
//    }
//
//    public String getUserLastname() {
//        return userLastname;
//    }
//
//    public void setUserLastname(String userLastname) {
//        this.userLastname = userLastname;
//    }
//
//    public Long getTrainStationId() {
//        return trainStationId;
//    }
//
//    public void setTrainStationId(Long trainStationId) {
//        this.trainStationId = trainStationId;
//    }
//
//    public String getModeOfPayment() {
//        return modeOfPayment;
//    }
//
//    public void setModeOfPayment(String modeOfPayment) {
//        this.modeOfPayment = modeOfPayment;
//    }
//
//    public LocalDateTime getTransactionDateTime() {
//        return transactionDateTime;
//    }
//
//    public void setTransactionDateTime(LocalDateTime transactionDateTime) {
//        this.transactionDateTime = transactionDateTime;
//    }
//
//    public double getAmount() {
//        return amount;
//    }
//
//    public void setAmount(double amount) {
//        this.amount = amount;
//    }
//
//    public String getDestinationName() {
//        return destinationName;
//    }
//
//    public void setDestinationName(String destinationName) {
//        this.destinationName = destinationName;
//    }
//
//    public String getCardNumber() {
//        return CardNumber;
//    }
//
//    public void setCardNumber(){
//        this.CardNumber = CardNumber;
//    }
//}



package com.backend.Ticket.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import java.time.LocalDateTime;

@Entity
public class Transactions {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Transaction ID, auto-generated by the database", accessMode = Schema.AccessMode.READ_ONLY)
    private Long transactionId;

    @Schema(description = "First name of the user", example = "John", required = true)
    private String userFirstname;

    @Schema(description = "Last name of the user", example = "Doe", required = true)
    private String userLastname;

    @Schema(description = "ID of the train station where the transaction occurred", example = "101", required = true)
    private Long trainStationId;

    @Schema(description = "Mode of payment used in the transaction", example = "Credit Card", required = true)
    private String modeOfPayment;

    @Schema(description = "Date and time of the transaction, auto-set by the system", accessMode = Schema.AccessMode.READ_ONLY, example = "2025-01-27T10:15:30")
    private LocalDateTime transactionDateTime;

    @Schema(description = "Total amount for the transaction", example = "50.75", required = true)
    private double amount;

    @Schema(description = "Destination station name", example = "Ayala Avenue")
    private String destinationName;  // New field for destination station name

    @Schema(description = "Card number", example = "1111222233334444")
    private String cardNumber; // Making this field nullable and dependent on the payment method

    // Default constructor
    public Transactions() {
        this.transactionDateTime = LocalDateTime.now(); // Automatically set the current date and time
    }

    // Getters and setters
    public Long getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    public String getUserFirstname() {
        return userFirstname;
    }

    public void setUserFirstname(String userFirstname) {
        this.userFirstname = userFirstname;
    }

    public String getUserLastname() {
        return userLastname;
    }

    public void setUserLastname(String userLastname) {
        this.userLastname = userLastname;
    }

    public Long getTrainStationId() {
        return trainStationId;
    }

    public void setTrainStationId(Long trainStationId) {
        this.trainStationId = trainStationId;
    }

    public String getModeOfPayment() {
        return modeOfPayment;
    }

    public void setModeOfPayment(String modeOfPayment) {
        this.modeOfPayment = modeOfPayment;
    }

    public LocalDateTime getTransactionDateTime() {
        return transactionDateTime;
    }

    public void setTransactionDateTime(LocalDateTime transactionDateTime) {
        this.transactionDateTime = transactionDateTime;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getDestinationName() {
        return destinationName;
    }

    public void setDestinationName(String destinationName) {
        this.destinationName = destinationName;
    }

    // This setter for cardNumber will now ensure that the card number is only set for card payments
    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
}
